http:
  port: "8080"

postgres:
    host: "localhost"
    port: "5433"
    username: "postgres"
    password: "root"
    database: "postgres"
    sslmode: "disable"

kafka:
  port: "9092"
  host: "localhost"
  topic: "orders"
  group_id: "order-consumer"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0