http:
  port: "8000"

postgres:
    host: "localhost"
    port: "5433"
    username: "postgres"
    password: "root"
    database: "postgres"
    sslmode: "disable"

kafka:
  brokers:
    - "localhost:9092"
  topic: "orders"
  group_id: "order-service"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0