http:
  port: "8080"

postgres:
  host: "postgres"
  port: "5432"
  username: "postgres"
  password: "postgres"
  database: "order"
  sslmode: "disable"

kafka:
  host: "kafka"
  port: "9092"
  topic: "order"
  group_id: "order-consumer"

redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0